language: ruby
sudo: false
script: 'ci/travis.rb'
before_install:
  - "rvm remove 2.2.3; true"
  - "rvm install 2.2.3 --patch https://t.co/ENYGvyloFf"
  - "rvm use 2.2.3"
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
branches:
  only:
    - 4-2-stable-tco-travis
cache: bundler
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
rvm:
  - 2.2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
      env: "GEM=ar:mysql"
    - rvm: 2.0.0
      env: "GEM=ar:mysql"
    - rvm: ruby-head
      env: "GEM=ar:mysql"
    - env: "GEM=aj:integration"
  fast_finish: true
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"
